- hosts: terraform-ansible
  tasks: 
  - name: criando o arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1> isso é um teste real ! </h1>

  - name: criando o servidor
    shell: "nohup busybox httpd -f -d 8080 &"
